apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-hello
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: hello=izumiiiii/hello:stg
    argocd-image-updater.argoproj.io/hello.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/argocd.force-update: 'true'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/staging
    repoURL: https://github.com/izumiiii/iu-test.git
    targetRevision: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true