apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-hello
  namespace: staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: izumiiiii/hello
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: master:image-updater-{{.SHA256}}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/staging
    repoURL: https://github.com/izumiiii/iu-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true