apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-hello
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: hello=izumiiiii/hello:stg
    argocd-image-updater.argoproj.io/hello.force-update: "true"
    argocd-image-updater.argoproj.io/hello.update-strategy: latest #2
    argocd-image-updater.argoproj.io/hello.ignore-tags: latest #3
    argocd-image-updater.argoproj.io/hello.allow-tags: regexp:^[0-9a-f]{5,40}$ #4
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/write-back-method: git #5
    argocd-image-updater.argoproj.io/git-branch: staging #6
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/staging
    repoURL: https://github.com/izumiiii/iu-test.git
    targetRevision: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true